load("@rules_java//java:defs.bzl", "java_import")

package(default_visibility = ["//visibility:public"])

java_import(
    name = "com_salesforce_revoman_revoman",
    jars = glob(
        ["revoman/build/libs/revoman-*.jar"],
        exclude = [
            "revoman/build/libs/revoman-*-sources.jar",
            "revoman/build/libs/revoman-*-javadoc.jar",
        ],
        allow_empty = False,
    ),
    srcjar = glob(
        ["revoman/build/libs/revoman-*-sources.jar"],
        allow_empty = False,
    )[0],
)
