= Contributing
Gopal S Akshintala <gopala.akshintala@salesforce.com>
:Revision: 1.0
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:hide-uri-scheme:
:sourcedir: src/main/java
:imagesdir: images
:revoman-version: 0.11.7
:toc:

[#_versioning_strategy]
== Versioning Strategy

====
<A>.<B>.<C>
====

* A = We broke something on purpose (Breaking API change)
* B = Profit (Feature / Improvement)
* C = We broke something by accident (Bug)

== Source-code Setup

=== Install Java 11

* It needs JDK 11 installed in your system. I recommend doing it via https://sdkman.io/install[SDKMAN]. After you install SDKMAN, run `sdk list java` -> Pick Identifier for your favorite java dist -> Run `sdk install java <Identifier-you-picked>  to install Java.

=== Build with Gradle

* This is a simple Gradle project and has its own Gradle wrapper. So nothing to install. Just run this command

[source,bash]
----
./gradlew clean build
----

TIP: You *don't* need a local Gradle installation as the `gradlew` (Gradle wrapper) takes care of everything. But if you wish to install gradle locally, the recommendation is to  do it via https://sdkman.io/install[SDKMAN]. After you install SDKMAN, run `sdk install gradle` to install Gradle

* You can run/debug the existing unit tests or write your own to play with the tool.

=== Kotlin

* The code-base is a mix of Java and Kotlin.
If you're a Java developer and new to Kotlin, don't worry, Kotlin is a JVM language and can be used anywhere Java is used.
In fact, it has got the reputation of *"Better Java!"*.
* A typical Java developer can ramp up on Kotlin in less than a week.
This free-course: https://www.coursera.org/learn/kotlin-for-java-developers[*Kotlin for Java Developers | Coursera*] can help catalyse your ramp-up.
* If you use Intellij, Kotlin plugin comes bundled.
Similar development aids should be present for other code editors too.

== Code Formatting

* This repo uses https://github.com/diffplug/spotless[*Spotless*] for formatting files, as this repo has code from more than one programming-language.
* Please run `./gradlew spotlessApply` before check-in to fix any formatting errors.

TIP: If you're on Intellij, replace your kbd:[Cmd+Shift+L] habit with kbd:[Ctrl]-kbd:[Ctrl] and run `gradle spotlessApply` (Or the respective action if you're on Eclipse).
It may be slow for the first run, but later runs should be faster.

== Manual publishing

This repo doesn't yet have the CI/CD pipeline.
So, it needs to be published manually.

* You need to add your nexus credentials in `~/.gradle/gradle.properties` file (create file if not present), which are used by your local gradle to connect to nexus to publish the jar.
** You can find your nexus userName and password from https://nexus.soma.salesforce.com/nexus/#profile;User%20Token[here] under the *User Token* section in the dropdown.
** If you are working on `core`, you can also get them from `core/workspace-user.xml` file.

[source,properties]
----
  nexusUsername=...
  nexusPassword=...
----

* Follow the <<_versioning_strategy,Versioning Strategy>> to increment version link:buildSrc/{sourcedir}/Config.kt[here]
** For SNAPSHOT releases, add a `-SNAPSHOT` at the end of version number
* Run this command to publish it to Nexus:

[source,bash]
----
./gradlew publish
----
