= Contributing
Gopal S Akshintala <gopala.akshintala@salesforce.com>
:Revision: 1.0
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:hide-uri-scheme:
:sourcedir: src/main/java
:imagesdir: images
:revoman-version: 0.5.5
:toc:

[#_versioning_strategy]
== Versioning Strategy

====
<A>.<B>.<C>
====

* A = We broke something on purpose (Breaking API change)
* B = Profit (Feature / Improvement)
* C = We broke something by accident (Bug)

== Source-code Setup

* This is a simple Gradle project and has its own Gradle wrapper.
So nothing to install.
Just run this command

[source,bash]
----
./gradlew clean build
----

* You can run/debug the existing unit tests or write your own to play with the tool.

[CAUTION]
====
While running Unit tests, you may encounter the classic `PKIX path building failed` issue with Java while making Http calls.To mitigate this,

- `<your-jdk-path>` — Locate the `jdk` being used by your Gradle
- `<your-cert-path>` — Fetch your host certificate and run the below command (rep) to add that cert to your java keystore
- `<some-name>` — Give any unique name

Run this command (When asked for `Enter keystore password:` enter `changeit` (Common for most Java distributions))

[source,bash]
----
keytool -import -alias <some-name> -keystore <your-jdk-path>/lib/security/cacerts -file <your-cert-path>.cer
----

For example:

[source,bash]
----
keytool -import -alias linux-4 -keystore /Users/gopala.akshintala/core-public/tools/Darwin/jdk/openjdk_17.0.5_17.38.22_x64/zulu-17.jdk/Contents/Home/lib/security/cacerts -file /Users/gopala.akshintala/Desktop/gopalaaksh-wsl4.internal.salesforce.com.cer
----

====

=== Kotlin

* The code-base is a mix of Java and Kotlin.
If you're a Java developer and new to Kotlin, don't worry, Kotlin is a JVM language and can be used anywhere Java is used.
In fact, it has got the reputation of *"Better Java!"*.
* A typical Java developer can ramp up on Kotlin in less than a week.
This free-course: https://www.coursera.org/learn/kotlin-for-java-developers[*Kotlin for Java Developers | Coursera*] can help catalyse your ramp-up.
* If you use Intellij, Kotlin plugin comes bundled.
Similar development aids should be present for other code editors too.

== Code Formatting

* This repo uses https://github.com/diffplug/spotless[*Spotless*] for formatting files, as this repo has code from more than one programming-language.
* Please run `./gradlew spotlessApply` before check-in to fix any formatting errors.

TIP: If you're on Intellij, replace your kbd:[Cmd+Shift+L] habit with kbd:[Ctrl]-kbd:[Ctrl] and run `gradle spotlessApply` (Or the respective action if you're on Eclipse).
It may be slow for the first run, but later runs should be faster.

== Manual publishing

This repo doesn't yet have the CI/CD pipeline.
So, it needs to be published manually.

* In link:build.gradle.kts[], follow the <<_versioning_strategy,Versioning Strategy>>
** For release increment the version property in link:buildSrc/src/main/kotlin/revoman.root-conventions.gradle.kts `version = "{revoman-version}"`
** For SNAPSHOT releases, add a `-SNAPSHOT` at the end
* Run this command:

[source,bash]
----
./gradlew publish
----
