$kind: http-request
url: "{{baseUrl}}/configure"
method: POST
headers:
  Content-Type: application/json
body:
  type: text
  content: |-
    {"productCode":"{{productCode}}","quantity":{{quantity}}}
scripts:
  - type: afterResponse
    code: |-
      var res = pm.response.json()
      pm.environment.set("configId", res.configId)
    language: text/javascript
order: 1000
