$kind: http-request
url: "{{baseUrl}}{{versionPath}}/sobjects/ProductRelationshipType"
method: POST
headers:
  Content-Type: application/json
  ignoreHTTPStatusUnsuccessful: "true"
body:
  type: text
  content: |-
    {
        "Name":"Bundle PRT",
        "MainProductRoleCat": "Bundle",
        "AssociatedProductRoleCat": "BundleComponent"
    }
scripts:
  - type: afterResponse
    code: |
      var jsonData = pm.response.json()
      pm.environment.set("productRelationshipTypeId", jsonData.id);
    language: text/javascript
order: 1000
