$kind: http-request
url: "{{baseUrl}}{{versionPath}}/query/?q=SELECT Id FROM PermissionSet WHERE Name IN ({{productAndPricingAdminPermSets}})"
method: GET
headers:
  Content-Type: application/json
queryParams:
  q: SELECT Id FROM PermissionSet WHERE Name IN ({{productAndPricingAdminPermSets}})
body:
  type: text
  content: ""
scripts:
  - type: afterResponse
    code: |-
      var jsonData = pm.response.json();
      jsonData.records.forEach((record, index) => {
          pm.environment.set("productAndPricingAdminPS" + (index + 1) + "Id", record.Id)
      })
    language: text/javascript
  - type: beforeRequest
    code: pm.environment.set("productAndPricingAdminPermSets", "'RevLifecycleManagementCalculatePricesApi', 'RevLifecycleManagementProductAndPriceConfigurationApi', 'RevLifecycleManagementProductImportApi', 'ProductCatalogManagementAdministrator', 'RevenueLifecycleManagementBillingAdmin'")
    language: text/javascript
order: 6000
